print('Onlinefeature1')
print('Onlinefeature2')
print('Onlinefeature3')
print('Localfeature4')
print('Localfeature5')
print('localfeature6')
print ('Onlinefeature7')
print ('Onlinefeature8')
print ('Onlinefeature9')
